# Makefile.config

ifeq ($(RELEASE),1)
	CXXFLAGS += -O3 -DNDEBUG -D_NDEBUG
	LDFLAGS += -mwindows -static-libgcc -static-libstdc++
else
	CXXFLAGS += -g -O0 -DDEBUG -D_DEBUG
endif

CXXFLAGS += -pipe -std=c++11 -Wall -Wextra -pedantic-errors

MAIN_BIN = same.exe
MAIN_SOURCES = $(wildcard ../src/*.cxx) $(wildcard ../src/same/*.cxx) \
			   $(wildcard ../src/same/ui/*.cxx)
MAIN_OBJECTS = $(MAIN_SOURCES:.cxx=.o)
MAIN_DEPENDS = $(MAIN_SOURCES:.cxx=.d)
MAIN_LIBS = -lgdi32 -lshlwapi -lwinmm

MAIN_RESOURCES = resources.o
MAIN_RCS = same.rc
MAIN_RC_DEPENDS = resource.h

TEST_BIN = test.exe
TEST_SOURCES = $(wildcard ../test/*.cxx) $(wildcard ../test/same/*.cxx)
TEST_OBJECTS = $(TEST_SOURCES:.cxx=.o) $(MAIN_OBJECTS)
TEST_DEPENDS = $(TEST_SOURCES:.cxx=.d)
TEST_LIBS = $(MAIN_LIBS) -lCppUTest -lCppUTestExt
