# Makefile.config

ifeq ($(RELEASE),1)
	CXXFLAGS += -O3 -DNDEBUG -D_NDEBUG
	LDFLAGS += -mwindows -static-libgcc -static-libstdc++
else
	CXXFLAGS += -g -O0 -DDEBUG -D_DEBUG
endif

CXXFLAGS += -pipe -std=c++17 -Wall -Wextra -Wold-style-cast -pedantic-errors -municode -D_UNICODE

MAIN_BIN = same.exe
MAIN_SOURCES = $(shell find ../src/ -type f -name \*.cxx -print)
MAIN_OBJECTS = $(MAIN_SOURCES:.cxx=.o)
MAIN_DEPENDS = $(MAIN_SOURCES:.cxx=.d)
MAIN_LIBS = -lgdi32 -lshlwapi -lwinmm

MAIN_RESOURCES = resources.o
MAIN_RCS = same.rc
MAIN_RC_DEPENDS = resource.h

TEST_BIN = test.exe
TEST_SOURCES = $(shell find ../test/ -type f -name \*.cxx -print)
TEST_OBJECTS = $(TEST_SOURCES:.cxx=.o) $(MAIN_OBJECTS)
TEST_DEPENDS = $(TEST_SOURCES:.cxx=.d)
TEST_LIBS = $(MAIN_LIBS) -lCppUTest -lCppUTestExt
